In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import numpy as np

In [3]:

iris = datasets.load_iris()
X = pd.DataFrame(iris.data)
X.columns = ['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width']
print(X)
y = pd.DataFrame(iris.target)
y.columns = ['Targets']
print(y)


     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]
     Targets
0          0
1          0
2          0
3          0
4          0
..       ...
145        2
146        2
147        2
148        2
149        2

[150 rows x 1 columns]


In [5]:

x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.1)
print("Dataset is split into training and testing...")
print("Size of training data and its label",x_train.shape,y_train.shape)
print("Size of testing data and its label",x_test.shape,y_test.shape)


Dataset is split into training and testing...
Size of training data and its label (135, 4) (135,)
Size of testing data and its label (15, 4) (15,)


In [7]:
from sklearn.svm import SVC
model=SVC()
SVC=model.fit(x_train,y_train)


In [9]:
y_pred=SVC.predict(x_test)
y_pred


array([2, 0, 2, 0, 1, 2, 1, 2, 2, 1, 0, 0, 0, 2, 0])

In [29]:
new_data_point = np.array([[6.1, 3.4, 4.6, 1.4]])
predicted_species_id = SVC.predict(new_data_point)
predicted_species_name = iris.target_names[predicted_species_id][0]

In [27]:

print("\nPrediction for new data point [6.1, 3.4, 4.6, 1.4]:")
print(f"Predicted Species: {predicted_species_name}")



Prediction for new data point [6.1, 3.4, 4.6, 1.4]:
Predicted Species: setosa


In [15]:

# Show which data points are the support vectors
print(f"\nNumber of support vectors: {len(SVC.support_vectors_)}")



Number of support vectors: 55


In [17]:
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred))
print('Accuracy Ketrics')
print(classification_report(y_test,y_pred))

Confusion Matrix
[[6 0 0]
 [0 3 0]
 [0 0 6]]
Accuracy Ketrics
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         6

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

