In [1]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
import pandas as pd
import numpy as np


In [3]:
iris = datasets.load_iris()
X = pd.DataFrame(iris.data)
X.columns = ['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width']
print(X)
y = pd.DataFrame(iris.target)
y.columns = ['Targets']
print(y)

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]
     Targets
0          0
1          0
2          0
3          0
4          0
..       ...
145        2
146        2
147        2
148        2
149        2

[150 rows x 1 columns]


In [11]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.1)
print("Dataset is split into training and testing...")
print("Size of training data and its label",x_train.shape,y_train.shape)
print("Size of testing data and its label",x_test.shape,y_test.shape)

Dataset is split into training and testing...
Size of training data and its label (135, 4) (135,)
Size of testing data and its label (15, 4) (15,)


In [13]:
# prints Label no. and their names
for i in range(len(iris.target_names)):
  print("Label", i , "-",str(iris.target_names[i]))


Label 0 - setosa
Label 1 - versicolor
Label 2 - virginica


In [15]:
#create object of KNN classifer
classifer = KNeighborsClassifier(n_neighbors=3)

In [17]:
#perform Training
classifer.fit(x_train, y_train)#perform teating
y_pred=classifer.predict(x_test)

In [19]:
#Display the results
print("Results of Classification using K-nn with K=3")
for r in range(0,len(x_test)):
  print(" sample:", str(x_test[r]), " Actual-label:",str(y_test[r]), " predict-label:", str(y_pred[r]))
print("Classification Accuracy :" , classifer.score(x_test,y_test))

Results of Classification using K-nn with K=3
 sample: [6.5 3.  5.2 2. ]  Actual-label: 2  predict-label: 2
 sample: [5.  3.5 1.3 0.3]  Actual-label: 0  predict-label: 0
 sample: [6.3 2.7 4.9 1.8]  Actual-label: 2  predict-label: 2
 sample: [5.8 2.7 3.9 1.2]  Actual-label: 1  predict-label: 1
 sample: [5.7 2.8 4.1 1.3]  Actual-label: 1  predict-label: 1
 sample: [5.  3.2 1.2 0.2]  Actual-label: 0  predict-label: 0
 sample: [6.3 3.4 5.6 2.4]  Actual-label: 2  predict-label: 2
 sample: [5.6 2.5 3.9 1.1]  Actual-label: 1  predict-label: 1
 sample: [5.7 3.  4.2 1.2]  Actual-label: 1  predict-label: 1
 sample: [5.  3.4 1.5 0.2]  Actual-label: 0  predict-label: 0
 sample: [5.1 3.7 1.5 0.4]  Actual-label: 0  predict-label: 0
 sample: [7.  3.2 4.7 1.4]  Actual-label: 1  predict-label: 1
 sample: [5.  3.  1.6 0.2]  Actual-label: 0  predict-label: 0
 sample: [4.8 3.  1.4 0.3]  Actual-label: 0  predict-label: 0
 sample: [5.3 3.7 1.5 0.2]  Actual-label: 0  predict-label: 0
Classification Accuracy 

In [21]:
from sklearn.metrics import classification_report, confusion_matrix
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred))
print('Accuracy Metrics')
print(classification_report(y_test,y_pred))

Confusion Matrix
[[7 0 0]
 [0 5 0]
 [0 0 3]]
Accuracy Metrics
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         5
           2       1.00      1.00      1.00         3

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

